import type { Metadata } from "next";
import { Rasa } from "next/font/google";
import "./styles/globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import RecoilContextProvider from "./recoil/recoilContextProvider";


const inter = Rasa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beauty(You)",
  description: "This is a portfolio page for a girl who specializes in eyelash care, created using TypeScript, React, Next.js, and FirebaseGenerated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilContextProvider>
          <div className={`
            ${inter.className}
            flex 
            justify-center 
            items-center 
            flex-col 
            h-full
            fontRasa
            bg-[url('../../public/background_media/background_general.png')]
            `}>
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </div>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
